
steps:
  - name: 'gcr.io/$PROJECT_ID/helm'
    args: ['upgrade', 'strimzi-operator', 'strimzi/strimzi-kafka-operator', '--install']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=gcp-gke-helm-poc'
      - 'HELM_REPO_NAME=strimzi'
      - 'HELM_REPO_URL=https://strimzi.io/charts/'
tags: ['cloud-builders-community']